# frozen_string_literal: true

require "spec_helper"

RSpec.describe StandardHealth::Redactor do
  # The exact shape of the leak this exists to stop.
  let(:leaky_result) do
    {
      status: :unavailable,
      checks: [
        { name: :database, critical: true, status: :fail,
          error: 'could not connect to server: Connection refused ' \
                 'host="db-prod.internal" port=5432 user="app_admin"',
          error_class: "PG::ConnectionBad" },
        { name: :cache, critical: false, status: :ok, latency_ms: 3 }
      ],
      generated_at: "2026-07-29T00:00:00Z"
    }
  end

  it "removes the raw driver message from a failing row" do
    row = described_class.call(leaky_result)[:checks].first

    expect(row).not_to have_key(:error)
    expect(row.to_s).not_to include("db-prod.internal")
    expect(row.to_s).not_to include("app_admin")
  end

  it "keeps the class name and adds a stable grouping code" do
    row = described_class.call(leaky_result)[:checks].first

    expect(row[:error_class]).to eq("PG::ConnectionBad")
    expect(row[:error_code]).to eq("pg_connection_bad")
  end

  it "leaves healthy rows byte-identical" do
    row = described_class.call(leaky_result)[:checks].last

    expect(row).to eq(name: :cache, critical: false, status: :ok, latency_ms: 3)
  end

  # Dashboards and existing specs read these; the release must not move them.
  it "preserves status, name, critical and latency on failing rows" do
    row = described_class.call(leaky_result)[:checks].first

    expect(row).to include(name: :database, critical: true, status: :fail)
    expect(described_class.call(leaky_result)[:status]).to eq(:unavailable)
    expect(described_class.call(leaky_result)[:generated_at]).to eq("2026-07-29T00:00:00Z")
  end

  it "passes everything through untouched when exposing" do
    expect(described_class.call(leaky_result, expose: true)).to eq(leaky_result)
  end

  it "supplies a class name when a row has a message but no class" do
    result = { checks: [{ name: :x, status: :fail, error: "bare" }] }

    row = described_class.call(result)[:checks].first

    expect(row[:error_class]).to eq("StandardError")
    expect(row).not_to have_key(:error)
  end

  # A :skipped row's message is generated by this gem from a config value, not
  # by a driver. It was never a leak vector, and it is the only thing that
  # explains a :degraded roll-up caused by budget exhaustion.
  describe "skipped rows" do
    let(:skipped) do
      {
        checks: [
          { name: :database, critical: true, status: :skipped,
            error: "skipped — total check budget of 5.0s exhausted" }
        ]
      }
    end

    it "keeps the explanation instead of relabelling it as StandardError" do
      row = described_class.call(skipped)[:checks].first

      expect(row[:error]).to match(/total check budget/)
      expect(row).not_to have_key(:error_class)
      expect(row).not_to have_key(:error_code)
    end
  end

  describe "error_code_for" do
    it "underscores namespaced camel-case class names" do
      expect(described_class.error_code_for("PG::ConnectionBad")).to eq("pg_connection_bad")
      expect(described_class.error_code_for("ActiveRecord::StatementInvalid"))
        .to eq("active_record_statement_invalid")
      expect(described_class.error_code_for("StandardHealth::CheckTimeout"))
        .to eq("standard_health_check_timeout")
    end
  end
end
